// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-DWQ9b-6TG3WY7NI4mKM0zNH79mLA6IE',
    appId: '1:531709576542:web:5e2773b49762d91866fbcf',
    messagingSenderId: '531709576542',
    projectId: 'social-a13b3',
    authDomain: 'social-a13b3.firebaseapp.com',
    storageBucket: 'social-a13b3.firebasestorage.app',
    measurementId: 'G-F99RRXJBJX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwSXzF9Cc4ltWm1UfudRxH7jltGHMdc0E',
    appId: '1:531709576542:android:4c140e7f1dc9144366fbcf',
    messagingSenderId: '531709576542',
    projectId: 'social-a13b3',
    storageBucket: 'social-a13b3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAkF7_eMfwTfCmd4C6zKcliVgtCmuligAU',
    appId: '1:531709576542:ios:450420106056651d66fbcf',
    messagingSenderId: '531709576542',
    projectId: 'social-a13b3',
    storageBucket: 'social-a13b3.firebasestorage.app',
    iosBundleId: 'com.example.social',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAkF7_eMfwTfCmd4C6zKcliVgtCmuligAU',
    appId: '1:531709576542:ios:450420106056651d66fbcf',
    messagingSenderId: '531709576542',
    projectId: 'social-a13b3',
    storageBucket: 'social-a13b3.firebasestorage.app',
    iosBundleId: 'com.example.social',
  );
}
